platform:ios,'7.0'
pod 'FMDB', '~> 2.6'
pod 'SDWebImage', '~> 3.7.5'
pod 'AFNetworking', '~> 3.0.4'
pod 'Masonry'
pod 'MJExtension'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDCycleScrollView', '~> 1.61'
pod 'FMDB', '~> 2.6'